require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end


#A common task for setting the server to reload every time a change is made. This is similar to nodemon
desc "Track and reload the server"
task :server do
  exec "rerun -b 'rackup config.ru'"
end#run using bundle exec rake server
